---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-deployment
  labels:
    app: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
        - name: go-demo
          image: harbor.prod.kubix.tm.com.my/concourse-demo/go-demo:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: LoadBalancer
  selector:
    app: go-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
