---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: go-demo
  labels:
    app: go-demo
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: default
      labels:
        app: go-demo
    spec:
      containers:
        - name: go-demo
          image: vsgdev/go-demo:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: go-demo
spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
  selector:
    app: demo-cicd
  type: LoadBalancer
